name: social_media_app
description: Social Media App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  firebase_storage: ^11.5.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  flutter_custom_clippers: ^2.1.0
  get: ^4.6.6
  image_picker: ^1.0.5
  image_cropper: ^5.0.1
  cached_network_image: ^3.3.0
  intl: ^0.19.0

  user_repository: 
    path: packages/login/user_repository

  post_repository: 
    path: packages/post/post_repository


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/


  fonts:
  - family: InterRegular
    fonts:
      - asset: assets/fonts/Inter-Regular.otf

  - family: InterMedium
    fonts:
      - asset: assets/fonts/Inter-Medium.otf

  - family: InterBold
    fonts:
      - asset: assets/fonts/Inter-Bold.otf

  - family: InterSemiBold
    fonts:
      - asset: assets/fonts/Inter-SemiBold.otf

      
  - family: Mantranaga
    fonts:
      - asset: assets/fonts/Mantranaga.otf

